[colors.bright]
black = "#7f7f7f"
blue = "#5c5cff"
cyan = "#00ffff"
green = "#008000"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#7f7fff"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#cd00cd"
red = "#cd0000"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.primary]
background = "#220022"
foreground = "#e5e5e5"

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[hints]
alphabet = "jfkdlsahgurieowpq"

[[hints.enabled]]
command = "url-menu"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "S"
mods = "Control"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
dynamic_title = true
